frontend:
  image: enessermaxhaj/enescoffe-frontend:v1.0
  port: 80

backend:
  image: enessermaxhaj/enescoffe-backend:v1.0
  port: 3000

postgres:
  image: postgres:17
  database: enesscoffee
  user: postgres
  password: password
  storage: 1Gi

ingress:
  host: enescoffe.local
  tlsSecret: enescoffe-tls
