name: EnessCoffee CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build frontend image
        run: |
          docker build \
            -t enessermaxhaj/enescoffe-frontend:${TAG} \
            ./frontend

      - name: Build backend image
        run: |
          docker build \
            -t enessermaxhaj/enescoffe-backend:${TAG} \
            ./backend

      - name: Push frontend image
        run: |
          docker push \
            enessermaxhaj/enescoffe-frontend:${TAG}

      - name: Push backend image
        run: |
          docker push \
            enessermaxhaj/enescoffe-backend:${TAG}